Создает разметку и стилизацию секции "Контакты"
CheekyGeroin/ice-cream-project pull request #10
Opened 2022-05-08 17:07 UTC by AnnNovy

2022-05-08 18:31 UTC, CheekyGeroin requested changes
Ань, так все супер, я отметил несколько моментов, которые нужно поменять, и пожалуйста поставь полный line-height везде где это надо:)

2022-05-08 18:31 UTC, CheekyGeroin commented on src/sass/_contacts.scss
> +    margin-left: 10px;
маржин должен быть 8px на первой кнопке и 13 на второй

2022-05-08 18:31 UTC, CheekyGeroin commented on src/sass/_contacts.scss
> +    margin-left: 10px;
добавь медиа запросы, в таблетке и на декстопе 13px на две кнопки

2022-05-08 18:31 UTC, CheekyGeroin commented on src/sass/_contacts.scss
> +    padding-bottom: 24px;
нужен медиа запрос, на таблетке и декстопе 32 px сверху снизу

2022-05-08 21:27 UTC, DaryaGrygorova commented on src/sass/_contacts.scss
> +
Для нижнього паддінгу зроби медіазапит 
@media screen and (max-width: $tablet - 1px) {
    padding-top: 8px;

тоді для таблетки та десктопу можна padding-top видалити - підтягне з базових для секціі

2022-05-08 21:33 UTC, DaryaGrygorova commented on src/sass/_contacts.scss
> +
Для мобілки залиш лише 
text-align: center;

а вже з таблетки - флекс:
  @media screen and (min-width: $tablet) {
    display: flex;
    align-items: center;
    justify-content: center;
  }

2022-05-08 21:35 UTC, DaryaGrygorova requested changes
Загалом дуже добре

2022-05-09 16:51 UTC, AnnNovy commented on src/partials/contacts.html
> +                <span class="contacts-category">CAFE</span>
Исправила

2022-05-09 16:51 UTC, AnnNovy commented on src/partials/contacts.html
> +        <ul class="buttons-list">
Исправила

2022-05-09 16:52 UTC, AnnNovy commented on src/sass/_contacts.scss
> +    line-height: 1.8;
Исправила

2022-05-09 16:52 UTC, AnnNovy commented on src/sass/_contacts.scss
> +    padding-bottom: 24px;
Исправила

2022-05-09 18:32 UTC, AnnNovy commented on src/sass/_contacts.scss
> +    margin-left: 10px;
Исправила

2022-05-09 18:32 UTC, AnnNovy commented on src/sass/_contacts.scss
> +
Исправила

2022-05-09 18:54 UTC, DaryaGrygorova approved these changes

2022-05-09 18:57 UTC, CheekyGeroin approved these changes

2022-05-09 18:57 UTC, merged